# Generated by Django 2.1.7 on 2019-03-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.CharField(blank=True, max_length=120, null=True)),
                ('available_status', models.CharField(choices=[('issued', 'Issued'), ('available', 'Available'), ('lost', 'Lost')], max_length=120)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('returned', 'Returned'), ('overdue', 'Over_Due')], default='pending', max_length=120)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('return_time', models.DateTimeField()),
                ('fine', models.IntegerField(default=0)),
                ('book_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmanagement.Issue')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='sachin', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('textbook', 'Text Book'), ('referencebook', 'Reference Book')], default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='hello', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmanagement.Book'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
